[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "stt-sdk"
# Pull version from stt_sdk.__init__.__version__
dynamic = ["version"]
description = "Async Python SDK for the STT service (auth, retries, pooling, telemetry)."
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.9"
license = { text = "MIT" }

authors = [{ name = "Your Team" }]
maintainers = [{ name = "Your Team" }]

classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Topic :: Software Development :: Libraries",
  "Topic :: Multimedia :: Sound/Audio",
]

dependencies = [
  "httpx>=0.27,<0.29",
]

[project.optional-dependencies]
dev = [
  "pytest>=7",
  "ruff>=0.4",
  "mypy>=1.6",
  "types-requests",
]

[project.urls]
Homepage = "https://example.com/stt-sdk"
Repository = "https://example.com/your/repo"
Issues = "https://example.com/your/repo/issues"

[tool.setuptools]
# If you prefer explicit inclusion:
# packages = ["stt_sdk"]

[tool.setuptools.packages.find]
include = ["stt_sdk"]

[tool.setuptools.dynamic]
version = { attr = "stt_sdk.__version__" }
